---
name: Bash Workflow
on:
  push:
    branches:
      - githubactions
  pull_request:
    branches:
      - githubactions
jobs:
  bash-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Message
        run: echo "Learn DevOps"